### ISSUE TITLE
Stack approach for "2.  Best Time to Buy and Sell Stock II"

### ISSUE THREAD

**Issue by harshchaplot** [HRKagdi/Leetcode-Top-100-Interview-Problems-#1]
Hey @HRKagdi! I would also like to contribute.

I was going through this problem "2.  Best Time to Buy and Sell Stock II" and wanted to suggest a stack-based solution.

Approach: Whenever we see an element greater than the top of the stack we pop it and find the profit we can make with this trade and we keep on doing that until we have an empty stack or we see an element greater than the current element(in which case we won't be able to make any profit). We take the maximum of the profit obtained here and add it to our total profit. If the stack is empty or the current element is greater than the top of the stack we simply push it onto the stack.

Code: https://pastebin.com/5KBueZAc

Also, we can approach this problem with constant space and O(n). In the previous approach we were(in the worst case) visiting every element twice, essentially making it O(2*n).

Approach: Every time we see an element greater than the previous element we add the difference to our profit and return this profit at the end. This works because we can sell and buy a stock on the same day. Also if we have something like [1,4,5], then usually what we do is buy on day 1 and sell on day 3 but since there are no restrictions on the number of trades we can make, we can buy on day 1 -> sell on day 2, again buy on day 2 -> sell on day 3 which yields us the same profit.

Code: https://pastebin.com/PUNu1htS

**Comment by HRKagdi** [comment]
@harshchaplot , Thanks for sharing your approach.
